### ISSUE TITLE
Remove JSONServiceClient ?

### ISSUE THREAD

**Issue by RayeN** [yola/demands#65]
Newer `requests` accept additional `json=` param, which allows us to make JSON-calls  e.g. 
`post(<SOME_URL>, json={...})` will actually do what our `JSONServiceClient` does.

Taking into account the above, I think we could remove `JSONServiceClient ` at all. Since it doesn't look very useful now.

What's your opinion?

**Comment by snitch** [comment]
@jslang: This issue is now a priority.
