### ISSUE TITLE
Proper name for `PaginatedAPIIterator`

### ISSUE THREAD

**Issue by RayeN** [yola/demands#67]
Technically it's not an iterator, but rather a container which supports iteration. And it's a bit misleading (I was wondering why I couldn't do `next()` over its instance).

The question here, should we rename it, to something less misleading (e.g. `PaginatedAPIResults` or anything better) or the current name is fine?

ping @yola/engineers

**Comment by beck** [comment]
Or implement a `.next`?

**Comment by jamesodo** [comment]
It's actually breaking a few rules of being an iterator.
`__iter__` should return `self` and `__next__` should raise `StopIteration` when finished.

I would vote for changing the behavior rather than a rename.

**Comment by jslang** [comment]
Since it's a generator why not `PaginatedAPGenerator`.

**Comment by RayeN** [comment]
Personally, I prefer to change name, because:

 - I still don't like an old name :) Even if it will be a real iterator. I read it as "Iterate over paginated API", but in fact, we do want to "iterate over paginated results of certain API"
 - `Python supports a concept of iteration over containers.` (that's from Python's manual).  And that perfectly describes current implementation - we have a container for paginated results for some API and we can iterate over those results. So, as I said, it's a container which supports iteration.
 - Making it just iterator means we'll limit its functionality.  For example, we can easily add support of `len(paginated_results)` later or some other container specific functions (based on API's meta, rather than on results).  And won't be able to do that with iterator.

Thoughts?

**Comment by jslang** [comment]
`PaginatedAPIResults` or even just `PaginatedResults` I think works fine for what you describe. I like your point about not constricting ourselves to an iterator.

**Comment by beck** [comment]
`PaginatedResults` - not too long and free of Hungarian notation 👍

**Comment by RayeN** [comment]
Yeah, and in the context of `demands`, it's probably clear what is the nature of those `results`.

**Comment by RayeN** [comment]
To summarize, are we all good with `PaginatedResults` ?

**Comment by jamesodo** [comment]
I vote yes.

**Comment by RayeN** [comment]
Cool, let's rename it then in the scope of this ticket.
