### ISSUE TITLE
Support `next` meta key as indicator of stop iteration

### ISSUE THREAD

**Issue by RayeN** [yola/demands#70]
A new version of DRF responds with 404 for an empty page (when page number > 1).  As result, we might end up with an error in our code when trying to iterate over pagination results.  E.g. for the cases when a number of resources is a multiple of page size (e.g. page_size = 10 and number of results is 20).

Proposed solution:  when we iterate over results - no need to request next page, if `next` meta key is null (indicator that the next page is empty).

**Comment by stefanor** [comment]
What's the logic for looking at the existence of the next key, but not following it? Is it because the URL may not be accurate in proxied situations?

I know of restful APIs (Google likes this pattern) that are paginated by *only* next/prev URLs. That way they can provide a consistent resultset across multiple pages.

**Comment by RayeN** [comment]
That's a good question.  I think we should just introduce a new `next` based pagination type since I don't see any reason to not follow next.  Will create a ticket for that.

**Comment by RayeN** [comment]
After looking at our current implementation - I don't think it will be trivial to implement that.  Right now our `PaginatedResults` is a wrapper around service method and service method encapsulates the details (and URL as well) how to get data from a certain endpoint (there might be some logic in it, for example).

**Comment by stefanor** [comment]
Yes, I think a paginater that used the next URL would have to hand the URL back to the service method.

**Comment by RayeN** [comment]
Created a ticket for that: https://github.com/yola/demands/issues/73
